### PR TITLE
Wookiee 2.4: Discovery, De-Akkafication, Helidon Webservice

### PR DESCRIPTION
**Pull request by malibuworkcrew**
* Support for an Akka-less Future
  - Created a new Mediator trait that's used for static object management
    + Global access to ActorSystem
  - Added a WookieeSupervisor to manage new non-akka executives, and to eventually replace HarnessActor
  - Added a new akka-less WookieeMonitor trait with health checks and other common functions
  - Created WookieeCommandExecutive (with tests) which is the new holder for V2 commands
  - Created new ComponentV2 that loads up without Akka and has the same functionality
    + Support in ComponentManager for message/request to V2 Components
    + Support for propagation of start, shutdown, and health check to a Component V2 and its children 
  - Created WookieeService parent and new ServiceV2 extensible
    + Support for Services that aren't akka-powered
    + Full monitoring (health and more) for ServiceV2
    + Removal of support for multiple Services on one Wookiee (not used)
  - Wookiee Actor Trait
    + Support for all common Actor operations
    + Queued execution and overrideable mailboxes
    + Support for state changes via 'become'
    + Support for stash() and unstashAll()
    + 100% code coverage
  - WookieeActorRouter trait and instantiation methods for making WookieeActor routers
    + RoundRobinRouter for simple routing
    + Support in V2 command structure for routers
  - New V2 command structure with typing and no akka dependency
  - TestHarness upgrades to handle V2 Services and Components
  - New WookieeOperations class which will have tools to emulate actors
  - Removed ActorLoggingAdapter and all references
  - Moved non-akka code out to a safe wookiee-libs module
  - Wookiee Metrics to ComponentV2
  - Wookiee Zookeeper to ComponentV2
  - Wookiee gRPC to Component V2
  - Wookiee Cache to Component V2
  - Wookiee Memcache to Component V2
* Creation of new module wookiee-discovery for akka-less gRPC clustering and messaging
  - New trait for DiscoverableCommand which supports gRPC messaging
  - Exec and Helper classes/traits to register/execute discoverable commands
  - More graceful catching of errors on discoverable gRPC executions
  - Detailed README
  - 100% test coverage
* Creation of new Component wookiee-web for web client and service hosting via helidon-web..
  - Created WookieeRouter to handle wildcards and endpoint routing using an efficient tree
  - Web Manager for endpoint registration and management of internal and external services
  - Support for HTTP query parameters, headers, and path segments
  - Error handling at each phase of processing
  - New WookieeHttpHandler which replaces AkkaHttpBase for OOP model of endpoint creation
  - Complete support of CORS specs for allowed Origins (config), Headers (per-endpoint), and Methods (dynamically populated)
  - OPTIONS call able to give details on any endpoint
  - WookieeHttpService trait for easy command adding
  - Full websocket support in wookiee-helidon
    + Compression support
    + OOP registration endpoint
    + Websocket CORS support
    + Websocket query/params support
    + Added functional endpoint for registration
    + WookieeWebsocket trait for OOP support
  - Added a WookieeWebClient powered by Helidon WebClient
    + Support for proxy hosts
  - Default endpoints (metrics/healthcheck)
  - Content type support  
  - SSL support
  - Detailed README
  - 100% test coverage
* Example project 'advanced-communication' that has two interconnected Services showing the use of wookiee-helidon and wookiee-discovery
  - Examples of functional and OOP usages of both HTTP and WS endpoints
  - Example of communication across services using Discoverable Commands
* Refactor of deeply deprecated patterns in wookiee-grpc-dev
* Creation of LoggingAdapterIO for IO wrapped logging
* Scalafmt to 3.7.11, guava to 32.1.1-jre, removal of log4cats, removal of slf4j-impl, akka downgrade to 2.6.20

### CODE REVIEW

**Comment by He-Pin** [comment]
@malibuworkcrew What about migrate to pekko, which is Apache V2 licensed and free.

**Comment by malibuworkcrew** [comment]
@He-Pin We have had some consideration of the Pekko project (which I’m glad people have taken on). However, we’re unsure of when it might leave incubation and what its long term support would be (which we’re especially reticent about due to the akka experience). As a result we have begun to hedge our bets and move towards less reliance on akka, with the potential goal of removing it from Wookiee altogether in a future version. This 2.4 release enables Wookiee implementations to optionally abstain from the use of akka patterns if they so choose.

**Comment by mdedetrich** [comment]
> @He-Pin We have had some consideration of the Pekko project (which I’m glad people have taken on). However, we’re unsure of when it might leave incubation and what its long term support would be (which we’re especially reticent about due to the akka experience)

While I think the decision has already been made I just wanted to clarify that Pekko leaving the incubator is the wrong metric to use to gauge "success" or "support". The more accurate metric is the actual release of Pekko modules itself and this is because to creating a release while within the Incubator has a very high bar (this is one of the main points of the incubator). This should be clear given that the requirement for promotion from an Incubator project to TLP (Top Level Project) is creating a few release + having a healthy community.

As you might already be aware, Pekko core has already been released with Pekko Http/Pekko Connectors Kafka on the horizon. If you have any more questions I would recommend reading/commenting on the mailing lists at https://lists.apache.org/list.html?dev@pekko.apache.org

**Comment by He-Pin** [comment]
@malibuworkcrew Understood, as a Oracle project, yes , move to another Oracle project is better for internal cooperation, and Yes, move to pekko will be much simpler at this now.

But, whatever the decision is, it came out with some reason, best wishes and looking  forward for all the goodies to come.

**Review by jayras-o — APPROVED** [review]
<thumbsUp/>

**Review by blavid — APPROVED** [review]

**Pull request merged**
